<?php

namespace AppBundle\Repository;

/**
 * Event_typeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Event_typeRepository extends \Doctrine\ORM\EntityRepository
{
}
