<?php

namespace AppBundle\Repository;

/**
 * StrategyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StrategyRepository extends \Doctrine\ORM\EntityRepository
{
}
