# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
     AppBundle.form.flow.registration:
         class: AppBundle\Form\RegistrationFlow
         parent: craue.form.flow
     app.provider.oauth:
         class: AppBundle\Security\Core\User\OAuthUserProvider
         arguments: ["@fos_user.user_manager",{google: googleID}]
     app.form.group:
         class: AppBundle\Form\GroupType
         tags:
             - { name: form.type, alias: app_bundle_group_type }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
