# src/AppBundle/Resources/config/doctrine/Permission.orm.yml
AppBundle\Entity\Permission:
    type: entity
    table: permission
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type:   string
            length: 255
            unique: true
        roles:
            column: roles
            type:   array
