# src/AppBundle/Resources/config/doctrine/User.orm.yml
AppBundle\Entity\User:
    type: entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        googleID:
            type: string
            nullable: false
            column: google_id